; ModuleID = 'FIRModule'
source_filename = "FIRModule"
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

@_QMep_dataECa = local_unnamed_addr constant double 0x41D2309CE5400000
@_QMep_dataECclass = local_unnamed_addr constant [1 x i8] c"B"
@_QMep_dataECcompiletime = local_unnamed_addr constant [11 x i8] c"12 Sep 2024"
@_QMep_dataECconvertdouble = local_unnamed_addr constant i32 0
@_QMep_dataECcs1 = local_unnamed_addr constant [6 x i8] c"(none)"
@_QMep_dataECcs2 = local_unnamed_addr constant [5 x i8] c"$(FC)"
@_QMep_dataECcs3 = local_unnamed_addr constant [6 x i8] c"(none)"
@_QMep_dataECcs4 = local_unnamed_addr constant [6 x i8] c"(none)"
@_QMep_dataECcs5 = local_unnamed_addr constant [6 x i8] c"(none)"
@_QMep_dataECcs6 = local_unnamed_addr constant [9 x i8] c"$(FFLAGS)"
@_QMep_dataECcs7 = local_unnamed_addr constant [6 x i8] c"randi8"
@_QMep_dataECm = local_unnamed_addr constant i32 30
@_QMep_dataECmk = local_unnamed_addr constant i32 16
@_QMep_dataECmm = local_unnamed_addr constant i32 14
@_QMep_dataECnk = local_unnamed_addr constant i32 65536
@_QMep_dataECnn = local_unnamed_addr constant i32 16384
@_QMep_dataECnpbversion = local_unnamed_addr constant [5 x i8] c"3.4.2"
@_QMep_dataECnq = local_unnamed_addr constant i32 10
@_QMep_dataEq = local_unnamed_addr global [10 x double] zeroinitializer
@_QMep_dataEqq = local_unnamed_addr global [10 x double] zeroinitializer
@_QMep_dataECs = local_unnamed_addr constant double 0x41B033C4D7000000
@_QMep_dataECt_gpairs = local_unnamed_addr constant i32 2
@_QMep_dataECt_last = local_unnamed_addr constant i32 4
@_QMep_dataECt_randn = local_unnamed_addr constant i32 3
@_QMep_dataECt_rcomm = local_unnamed_addr constant i32 4
@_QMep_dataECt_total = local_unnamed_addr constant i32 1
@_QMep_dataEx = local_unnamed_addr global [131072 x double] zeroinitializer

!llvm.module.flags = !{!0, !1, !2, !3}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !{i32 7, !"openmp", i32 11}
!2 = !{i32 8, !"PIC Level", i32 2}
!3 = !{i32 7, !"PIE Level", i32 2}
