PACKAGE_TARNAME = papi
prefix = /home/studyztp/test_ground/experiments/hardware-profiling/NPB_protocol/NPB3.4.2/NPB3.4-OMP/common/papi/src/../../all_papi/x86_64
exec_prefix = ${prefix}
datarootdir = ${prefix}/share
datadir = ${datarootdir}/${PACKAGE_TARNAME}
DATADIR = $(DESTDIR)$(datadir)
INCLUDE = -I. -I${prefix}/include
CC	= gcc
F77	= gfortran
CC_R	= $(CC) -pthread
CFLAGS	=  -g -Wextra  -Wall -DPAPI_NUM_COMP=3 -O1
ENABLE_FORTRAN = yes
